#!/usr/bin/env node
/**
 * Downloads every runtime asset for NIGHT OF THE RISEN from the web.
 *
 *   node tools/fetch-assets.mjs [--force]
 *
 * Reads tools/assets.manifest.json. Skips files that already exist unless
 * --force is passed. Zero npm dependencies — uses the built-in fetch.
 */
import { readFile, mkdir, writeFile, stat } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const force = process.argv.includes('--force');

const manifest = JSON.parse(await readFile(resolve(root, 'tools/assets.manifest.json'), 'utf8'));

const expand = (src) => {
  const i = src.indexOf(':');
  const base = manifest.bases[src.slice(0, i)];
  if (!base) throw new Error(`unknown base in "${src}"`);
  return `${base}/${src.slice(i + 1)}`;
};

/**
 * Removes every texture reference from a .gltf.
 *
 * The Poly Haven props are mirrored as geometry and a buffer with no images
 * beside them, but their glTF still names three maps per material. Loaded
 * as-is, each one is a 404 at runtime and the material comes out with dangling
 * texture slots. These models are re-finished with the game's own materials
 * anyway, so the references are dropped here rather than worked around later.
 */
function stripTextures(buf, label) {
  const doc = JSON.parse(buf.toString('utf8'));
  const had = (doc.images || []).length;
  delete doc.images;
  delete doc.textures;
  delete doc.samplers;
  for (const m of doc.materials || []) {
    delete m.normalTexture;
    delete m.occlusionTexture;
    delete m.emissiveTexture;
    const pbr = m.pbrMetallicRoughness;
    if (pbr) { delete pbr.baseColorTexture; delete pbr.metallicRoughnessTexture; }
  }
  if (had) console.log(`         stripped ${had} texture reference(s) from ${label}`);
  return Buffer.from(JSON.stringify(doc));
}

const exists = async (p) => { try { return (await stat(p)).size > 0; } catch { return false; } };

const kb = (n) => `${(n / 1024).toFixed(0)} KB`;

let downloaded = 0, skipped = 0, failed = 0, bytes = 0;

for (const asset of manifest.assets) {
  const dst = resolve(root, asset.dst);
  if (!force && await exists(dst)) {
    skipped++;
    console.log(`  skip   ${asset.dst}`);
    continue;
  }
  const url = expand(asset.src);
  try {
    const res = await fetch(url, { redirect: 'follow' });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    let buf = Buffer.from(await res.arrayBuffer());
    if (buf.length === 0) throw new Error('empty body');
    if (asset.strip === 'textures') buf = stripTextures(buf, asset.dst);
    await mkdir(dirname(dst), { recursive: true });
    await writeFile(dst, buf);
    downloaded++; bytes += buf.length;
    console.log(`  get    ${asset.dst}  (${kb(buf.length)})`);
  } catch (err) {
    failed++;
    console.error(`  FAIL   ${asset.dst}  <- ${url}\n         ${err.message}`);
  }
}

// Several of these assets are CC-BY, which obliges us to credit them where
// players can see it. Generating the credits from the manifest means they can
// never drift out of date as assets are added or swapped.
const credits = new Map();
for (const a of manifest.assets) {
  const key = a.license;
  if (!credits.has(key)) credits.set(key, []);
  credits.get(key).push(a.dst.replace(/^assets\//, ''));
}
const creditsDoc = {
  note: 'Generated by tools/fetch-assets.mjs. Do not edit by hand.',
  generated: new Date().toISOString().slice(0, 10),
  entries: [...credits.entries()]
    .map(([license, files]) => ({ license, files: files.sort() }))
    .sort((a, b) => a.license.localeCompare(b.license)),
};
await writeFile(resolve(root, 'assets/credits.json'), JSON.stringify(creditsDoc, null, 2) + '\n');
console.log(`  wrote  assets/credits.json (${creditsDoc.entries.length} licences)`);

console.log(`\n${downloaded} downloaded (${kb(bytes)}), ${skipped} already present, ${failed} failed.`);
process.exit(failed ? 1 : 0);
